name: Build Sintco Sparxmaths Solver and Release
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build codebase and release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get current unix seconds
        id: unix
        run: |
          echo "value=$(date +'%s')" >> $GITHUB_OUTPUT

      - name: Get version
        id: version
        run: |
          version=$(cat ./extension/manifest.json | grep -oE '[ ]+"version": "(.*)",' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "value=$version" >> $GITHUB_OUTPUT
        
      - name: Install dependencies
        id: dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Build codebase
        id: build
        run: pnpm build

      - name: Compress `dist` directory
        id: compress
        run: |
          mv dist sparxmaths-${{ steps.version.outputs.value }}
          zip -r Sintco-Sparxmaths-Solver.zip sparxmaths-${{ steps.version.outputs.value }} & wait $!;

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: azalea-${{ steps.unix.outputs.value }}
          title: "Sintco Sparxmaths Solver ${{ steps.version.outputs.value }}"
          files: ./*.zip
