name: Build and Release Sintco Sparxmaths Solver

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build codebase and release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current unix seconds
        id: unix
        run: |
          echo "value=$(date +'%s')" >> $GITHUB_ENV

      - name: Get version
        id: version
        run: |
          version=$(cat ./extension/manifest.json | grep -oE '[ ]+"version": "(.*)",' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "value=$version" >> $GITHUB_ENV
        
      - name: Install dependencies
        id: dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Build codebase
        id: build
        run: pnpm build

      - name: Compress dist directory
        id: compress
        run: |
          mv dist sparxmaths-${{ steps.version.outputs.value }}
          zip -r sparxmaths.zip sparxmaths-${{ steps.version.outputs.value }} & wait $!;

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Sintco Sparxmaths Solver ${{ steps.version.outputs.value }}"
          files: ./*.zip
